-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 15:37:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema savinganimal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema savinganimal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `savinganimal` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `savinganimal` ;

-- -----------------------------------------------------
-- Table `savinganimal`.`donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `savinganimal`.`donor` (
  `donorID` INT NOT NULL AUTO_INCREMENT,
  `donorName` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `donorSurrogate` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `donorAddress` VARCHAR(225) CHARACTER SET 'utf8mb4' NOT NULL,
  `donorEmail` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `donorPhone` VARCHAR(11) CHARACTER SET 'utf8mb4' NOT NULL,
  `donorMoney` DOUBLE NOT NULL,
  `donorTotalMoney` DOUBLE NOT NULL,
  `donorImage` VARCHAR(225) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`donorID`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `savinganimal`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `savinganimal`.`employee` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `employeeName` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `employeePosition` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `employeeGroup` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `employeeDescription` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `employeeDOB` DATE NOT NULL,
  `employeeDegree` VARCHAR(30) CHARACTER SET 'utf8mb4' NOT NULL,
  `employeeEmail` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `employeePhone` VARCHAR(11) CHARACTER SET 'utf8mb4' NOT NULL,
  `employeeAddress` VARCHAR(225) CHARACTER SET 'utf8mb4' NOT NULL,
  `employeeCMND` VARCHAR(15) CHARACTER SET 'utf8mb4' NOT NULL,
  `employeeProvinceCode` INT NOT NULL,
  `employeeImage` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `employeeGender` VARCHAR(10) CHARACTER SET 'utf8mb4' NOT NULL,
  `employeeJoinDate` DATE NOT NULL,
  PRIMARY KEY (`employeeID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `savinganimal`.`provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `savinganimal`.`provinces` (
  `provinceID` INT NOT NULL AUTO_INCREMENT,
  `provinceName` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `provinceCode` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`provinceID`))
ENGINE = InnoDB
AUTO_INCREMENT = 72
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `savinganimal`.`reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `savinganimal`.`reports` (
  `reportID` INT NOT NULL AUTO_INCREMENT,
  `reportAddress` VARCHAR(225) CHARACTER SET 'utf8mb4' NOT NULL,
  `reportDescription` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `reportPersonName` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `reportEmail` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `reportPhone` VARCHAR(11) CHARACTER SET 'utf8mb4' NOT NULL,
  `reportStatus` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`reportID`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
